use_frameworks!

platform :ios, '9.0'

target 'Gauge_Example' do
  pod 'Gauge', :path => '../'

  target 'Gauge_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase' , '~> 2.1.4'
  end
end
